--Item entry Template
-- [] = {
--  name = '',
--  fancy_name = '',
--  id = ,
--  sprite_id = ,
--  belt_id = ,
--  color_key = 0,
--  type = '',
--  sub_type = '',
--  stack_size = ,
--  recipe = {
--  id = 20,
--  crafting_time = 120,
--  count = 1,
--  ingredients = {
--    [1] = {id = 15, count = 2}
--  }
-- }

----ITEMS----
-- 3  = 'iron_ore'
-- 4  = 'copper_ore'
-- 6  = 'coal_ore'
-- 5  = 'stone_ore'
-- 8  = 'oil_shale'
-- 7  = 'uranium'
-- 0  = 'raw_wood'
-- 15 = 'iron_plate'
-- 20 = 'gear'
-- 16 = 'copper_plate'
-- 21 = 'copper_cable'
-- 17 = 'stone_brick'
-- 0  = 'plastic_bar'
-- 0  = 'iron_stick'
-- 14 = 'stone_furnace'
-- 13 = 'mining_drill'
-- 9  = 'transport_belt'
-- 18 = 'underground_belt'
-- 10 = 'splitter'
-- 11 = 'inserter'
-- 2  = 'electronic_circuit'
-- 1  = 'advanced_circuit'
-- 0  = 'processing_unit'
-- 12 = 'power_pole'
-- 19 = 'assembly_machine'
-- 0  = 'wooden_chest'
-- 0  = 'iron_chest'
-- 0  = 'steel_chest'
-- 0  = 'lab'
-- 0  = ''
-- 0  = ''
-- 0  = ''
-- 0  = ''
-- 0  = ''
-- 0  = ''
-- 0  = ''